config/routes.rb
Rails.application.routes.draw do
  root to: 'homes#top'
  get 'home/about' => 'homes#about',as:"about"
  devise_for :users

  resources:users, only:[:index,:edit,:show,:update] do
    get "searchBookCount" => "users#searchBookCount"
    resource :relationships, only: [:create, :destroy] do
      member do
        get :follows, :followers
      end
    end
  end
  get "search_book" => "searches#searchBook"
  get "search_user" => "searches#searchUser"

  resources:books, only:[:index,:edit,:show,:create,:destroy,:update] do
    resource:favorites, only: [:create,:destroy]
    resources:book_comments, only: [:create,:destroy]
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController

  def create
    current_user.follow(params[:user_id])
    @user = User.find(params[:user_id])
  end

  def destroy
    current_user.unfollow(params[:user_id])
    @user = User.find(params[:user_id])
  end

  def follows
    user = User.find(params[:user_id])
    @users = user.following_user
  end

  def followers
    user = User.find(params[:user_id])
    @users = user.follower_user
  end

end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/views/relationships/_follow_btn.html.erb
<% if current_user.following?(user) %>
  <%= link_to "Unfollow", user_relationships_path(user.id), method: :delete, class:"btn btn-outline-danger btn-block", remote: true %>
<% else %>
  <%= link_to "Follow", user_relationships_path(user.id), method: :post, class:"btn btn-outline-info btn-block",  remote: true %>
<% end %>

app/views/relationships/_follow_count.html.erb
<%= link_to user.following_user.count, follows_user_relationships_path(user.id)  %>

app/views/relationships/_follower_count.html.erb
<%= link_to user.follower_user.count, followers_user_relationships_path(user.id) %>

app/views/relationships/create.js.erb
$('.follow_btn').html("<%= j(render 'relationships/follow_btn', user: @user ) %>");
$('#follow_count').html("<%=j(render 'relationships/follow_count', user: @user )  %>");
$('#follower_count').html("<%= j(render 'relationships/follower_count', user: @user ) %>");

app/views/relationships/destroy.js.erb
$('.follow_btn').html("<%= j(render 'relationships/follow_btn', user: @user ) %>");
$('#follow_count').html("<%=j(render 'relationships/follow_count', user: @user )  %>");
$('#follower_count').html("<%= j(render 'relationships/follower_count', user: @user ) %>");

app/views/relationships/followers.html.erb
<div class="container">
  <div class="row">
    <div class="col-lg-10">
      <% if @users.exists? %>
      <h4>Follow Users</h4>
        <table class="table">
          <tr>
            <th></th>
            <th>Name</th>
            <th>Follow</th>
             <th>Follower</th>
            <th></th>
          </tr>
          <% @users.each do |user| %>
            <tr>
              <td><%= image_tag user.icon(80,80) %></td>
              <td><%= user.name %></td>
              <td><%= link_to user.following_user.count, follows_user_relationships_path(user.id) %></td>
              <td><%= link_to user.follower_user.count, followers_user_relationships_path(user.id) %></td>
              <td><%= link_to "Show", user_path(user.id) %></td>
            </tr>
          <% end %>
        </table>
      <% else %>
        <p>ユーザーはいません</p>
      <% end %>
    </div>
  </div>
</div>

app/views/relationships/follows.html.erb
<div class="container">
  <div class="row">
    <div class="col-lg-10">
      <% if @users.exists? %>
      <h4>Follow Users</h4>
        <table class="table">
          <tr>
            <th></th>
            <th>Name</th>
            <th>Follow</th>
             <th>Follower</th>
            <th></th>
          </tr>
          <% @users.each do |user| %>
            <tr>
              <td><%= image_tag user.icon(80,80) %></td>
              <td><%= user.name %></td>
              <td><%= link_to user.following_user.count, follows_user_relationships_path(user.id) %></td>
              <td><%= link_to user.follower_user.count, followers_user_relationships_path(user.id) %></td>
              <td><%= link_to "Show", user_path(user.id) %></td>
            </tr>
          <% end %>
        </table>
      <% else %>
        <p>ユーザーはいません</p>
      <% end %>
    </div>
  </div>
</div>