config/routes.rb
Rails.application.routes.draw do
  root to: 'homes#top'
  get 'home/about' => 'homes#about',as:"about"
  devise_for :users

  resources:users, only:[:index,:edit,:show,:update] do
    get "searchBookCount" => "users#searchBookCount"
    resource :relationships, only: [:create, :destroy] do
      member do
        get :follows, :followers
      end
    end
  end
  get "search_book" => "searches#searchBook"
  get "search_user" => "searches#searchUser"

  resources:books, only:[:index,:edit,:show,:create,:destroy,:update] do
    resource:favorites, only: [:create,:destroy]
    resources:book_comments, only: [:create,:destroy]
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user
  has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy
   validates:title,presence:true
   validates:body,presence:true,length:{maximum: 200 }

   def favorited_by?(user)
     favorites.exists?(user_id: user.id)
   end

  def self.search(keyword)
    where(["title LIKE? OR body LIKE?", "%#{keyword}%", "%#{keyword}%"])
  end

  scope :created_this_week, -> { where(created_at: 6.days.ago.beginning_of_day..Time.zone.now.end_of_day) }
  scope :created_last_week, -> { where(created_at: 2.week.ago.beginning_of_day..1.week.ago.end_of_day) }
  scope :created_each_date, -> (date){ where(created_at: date.days.ago.all_day) }
  def self.book_week_count
    (0..6).map { |date| created_each_date(date).count }.reverse
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  before_action:is_maching_login_user,only:[:edit,:update,:destroy]

  def index
    @book = Book.new
    @books = Book.all
  end

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      flash[:notice] ="You have created book successfully."
      redirect_to book_path(@book.id)
    else
      @books = Book.all
      render:index
    end
  end

  def show
    @book =Book.find(params[:id])
    @book_new = Book.new
    @comment = BookComment.new
  end

  def edit
    @book = Book.find(params[:id])
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
     flash[:notice] ="You have updated book successfully."
     redirect_to book_path(@book.id)
    else
      render:edit
    end
  end

  def destroy
    book = Book.find(params[:id])
    book.destroy
    flash[:notice] ="You have destroyed book successfully."
    redirect_to books_path
  end

  private

  def book_params
    params.require(:book).permit(:title,:body)
  end

  def is_maching_login_user
    book = Book.find(params[:id])
    unless book.user_id == current_user.id
      redirect_to books_path
    end
  end
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_template.html.erb
<h2>User info</h2>
  <%= image_tag user.icon(100,100) %>
 <table class="table">
      <tr></tr>
      <tr>
        <th>name</th>
        <th><%= user.name %></th>
      </tr>
      <tr>
       <th>introduction</th>
       <th><%= user.introduction %></th>
      </tr>
 </table>

  <% if current_user == user %>
    <%= link_to edit_user_path(user.id),class:"btn btn-outline-secondary btn-block" do %>
      <i class="fas fa-user-cog"></i>
    <% end %>
  <% else %>
    <div class="follow_btn">
      <%= render "relationships/follow_btn", user: user %>
    </div>
  <% end %>
  
  <table class="table">
  <tr>
    <th>follow</th>
    <th id="follow_count">
      <%= render 'relationships/follow_count', user: user %>
    </th>
  </tr>
  <tr>
    <th>follower</th>
    <th id="follower_count">
      <%= render 'relationships/follower_count', user: user %>
    </th>
  </tr>
</table>

<div class="form-group mt-3">
  <h2>New book</h2>
  <%= form_with model: book do |f| %>
    <div class="form">
      <p class="mb-1 mt-3">Title</p>
      <%= f.text_field :title,class:"form-control" %>
    </div>
    <div class="form">
      <p class="mb-1 mt-3">Opinion</p>
      <%= f.text_area :body, class:"form-control" %><br />
      <%= f.submit "Create Book", class:"btn btn-success" %>
    </div>
  <% end %>
</div>

app/views/books/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-5 mx-auto pt-3">
      <h1>Editing Book</h1>
        <% if @book.errors.any? %>
          <h3><%= pluralize(@book.errors.count,"error") %>prohibited this obj from being saved:</h3><br />
            <ul>
              <% @book.errors.full_messages.each do |message| %>
                <li><%= message %></li>
              <% end %>
            </ul>
        <% end %>

      <%= form_with model: @book do |f| %>
        <p>Title
        <%= f.text_field:title,class:"form-control" %></p>
        <p>Opinion
        <%= f.text_area:body,class:"form-control mb-0" %></p><br />
        <%= f.submit "Update Book",class:"btn btn-success text-white mb-3 mt-0" %>
      <% end %>
      <%= link_to "Show", book_path(@book.id) %> |
      <%= link_to "Back", books_path %>
    </div>
  </div>
</div>

app/views/books/index.html.erb
<div class="ml-5">
  <% if @book.errors.any? %>
    <h3><%= pluralize(@book.errors.count,"error") %>prohibited this obj from being saved:</h3><br />
      <ul>
        <% @book.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
  <% end %>
</div>

<div class="container">
  <div class="row">
    <div class="col-md-3 mt-3">
      <%= render'template', book: @book, user: current_user %>
    </div>

    <div class="col-md-8 offset-md-1 mt-3">

      <h2>Books</h2>
      <div class="float-right">
 
        <%= render 'searches/search_Book' %>
      </div>
        <table class="table">
          <thead>
            <tr>
              <th></th>
              <th>Title</th>
              <th>Opinion</th>
              <th></th>
              <th></th>
            </tr>
          </thead>
          <tbody>
            <% @books.each do |book| %>
              <tr>
                <td><%= image_tag book.user.icon(80,80) %><br />
                    <%= link_to book.user.name, user_path(book.user.id) %></td>
                <td><%= link_to book.title, book_path(book.id) %></td>
                <td><%= book.body %></td>
                <th>コメント数：<%= book.book_comments.count %></th>
                <td class="favorite_<%= book.id %>"><%= render 'favorites/favorite', book: book %></td>
              </tr>
            <% end %>
          </tbody>
        </table>
    </div>
  </div>
</div>

app/views/books/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-3 mt-3">
      <%= render'template', book: @book_new,user: @book.user, following_users: @following_users, follower_users: @follower_users  %>
    </div>
    <div class="col-md-8 offset-md-1 mt-3">
      <h2>Book detail</h2>
      <table class="table">
        <tbody>
          <tr>
            <th><%= image_tag @book.user.icon(100,100) %><br>
                <%= link_to @book.user.name,user_path(@book.user_id) %></th>
            <th><%= @book.title %></th>
            <th><%= @book.body %></th>
            <th id="comment_count">コメント数：<%= @book.book_comments.count %></th>
            <td class="favorite_<%= @book.id %>"><%= render 'favorites/favorite', book: @book %></td>
            <% if @book.user == current_user %>
              <th><%= link_to "Edit",edit_book_path(@book.id),class:"btn btn-success" %></th>
              <th><%= link_to "Destroy",book_path,method: :delete ,class:"btn btn-danger",data: { confirm: "Are you sure?" } %></th>
            <% end %>
          </tr>
        </tbody>
      </table>
      <div id="comment">
        <%= render 'book_comments/bookComment', book: @book %>
      </div>
      <div id="form_<%= @book.id %>">
        <%= render 'book_comments/form', book: @book, comment: @comment %>
      </div>
      
    </div>
  </div>
</div>