config/routes.rb
Rails.application.routes.draw do
  root to: 'homes#top'
  get 'home/about' => 'homes#about',as:"about"
  devise_for :users

  resources:users, only:[:index,:edit,:show,:update] do
    get "searchBookCount" => "users#searchBookCount"
    resource :relationships, only: [:create, :destroy] do
      member do
        get :follows, :followers
      end
    end
  end
  get "search_book" => "searches#searchBook"
  get "search_user" => "searches#searchUser"

  resources:books, only:[:index,:edit,:show,:create,:destroy,:update] do
    resource:favorites, only: [:create,:destroy]
    resources:book_comments, only: [:create,:destroy]
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController

  def searchBook
    @book = Book.new
    @books = Book.search(params[:keyword])
    @keyword = params[:keyword]
  end

  def searchUser
    @book = Book.new
    @users = User.search(params[:keyword])
    @keyword = params[:keyword]
  end
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/views/searches/_search.html.erb
<% if user_signed_in? %>
  <div class="seach_form">
    <%= form_with url: search_path, method: :get do |f| %>
      <%= f.text_field :keyword, value: @keyword %>
      <%= f.submit 'seach', class:"btn btn-info" %>
    <% end %>
  </div>
<% end %>

app/views/searches/_search_Book.html.erb
<% if user_signed_in? %>
  <div class="seach_form">
    <%= form_with url: search_book_path, method: :get do |f| %>
      <%= f.text_field :keyword, value: @keyword %>
      <%= f.submit 'seach', class:"btn btn-info" %>
    <% end %>
  </div>
<% end %>

app/views/searches/_search_User.html.erb
<% if user_signed_in? %>
  <div class="seach_form">
    <%= form_with url: search_user_path, method: :get do |f| %>
      <%= f.text_field :keyword, value: @keyword %>
      <%= f.submit 'seach', class:"btn btn-info" %>
    <% end %>
  </div>
<% end %>

app/views/searches/search.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-3 mt-3">
      <%= render'books/template', book: @book,user: current_user %>
    </div>

    <div class="col-md-8 offset-md-1 mt-3">

      <h2>Books 検索結果</h2>
      <div class="float-right">
        <%= link_to "戻る", :back %>
      </div>
        <table class="table">
          <thead>
            <tr>
              <th></th>
              <th>Title</th>
              <th>Opinion</th>
              <th></th>
            </tr>
          </thead>
          <tbody>
            <% @books.each do |book| %>
              <tr>
                <td><%= image_tag book.user.icon(80,80) %><br />
                    <%= link_to book.user.name, user_path(book.user.id) %></td>
                <td><%= link_to book.title, book_path(book.id) %></td>
                <td><%= book.body %></td>
                <td class="favorite_<%= book.id %>"><%= render 'favorites/favorite', book: book %></td>
              </tr>
            <% end %>
          </tbody>
        </table>
    </div>
  </div>
</div>

app/views/searches/searchBook.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-3 mt-3">
      <%= render'books/template', book: @book,user: current_user %>
    </div>

    <div class="col-md-8 offset-md-1 mt-3">

      <h2>Books 検索結果</h2>
      <div class="float-right">
        <%= link_to "戻る", :back %>
      </div>
        <table class="table">
          <thead>
            <tr>
              <th></th>
              <th>Title</th>
              <th>Opinion</th>
              <th></th>
            </tr>
          </thead>
          <tbody>
            <% @books.each do |book| %>
              <tr>
                <td><%= image_tag book.user.icon(80,80) %><br />
                    <%= link_to book.user.name, user_path(book.user.id) %></td>
                <td><%= link_to book.title, book_path(book.id) %></td>
                <td><%= book.body %></td>
                <td class="favorite_<%= book.id %>"><%= render 'favorites/favorite', book: book %></td>
              </tr>
            <% end %>
          </tbody>
        </table>
    </div>
  </div>
</div>

app/views/searches/searchUser.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-3 mt-3">
      <%= render'books/template', book: @book, user: current_user %>
    </div>
    <div class="col-md-8 offset-md-1 mt-3">
      <h2>Users 検索結果</h2>
      <div class="float-right">
        <%= link_to "戻る", :back %>
      </div>
        <table class="table">
          <thead>
            <tr>
              <th>image</th>
              <th>name</th>
              <th></th>
              <th></th>
            </tr>
          </thead>
          <% @users.each do |user| %>
            <tbody>
              <tr>
                <td><%= image_tag user.icon(80,80) %></td>
                <td><%= user.name %></td>
                <td><%= link_to"Show", user_path(user.id) %></td>
              </tr>
            </tbody>
          <% end %>
        </table>
    </div>
  </div>
</div>